# Site settings
title: Whatevertown
subtitle: "A podcast by Jon Dueck, Ryan Kehler, and Tim Wall."
email: whatevertownpod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whatevertown is a podcast by Jon Dueck, Ryan Kehler, and Tim Wall. It's a show about pop culture, art, the internet, and whatever.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whatevertown.com" # the base hostname & protocol for your site
permalink: /:title
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty
exclude: ['/node_modules/','**.sublime-project','**.sublime-workspace','gulpfile.js','package.json','.git','README.md']
lang: en
author: Whatevertown
copyright: "&#xA9; 2015"
artwork: /assets/img/artwork.png

# Build settings
markdown: kramdown
theme: null

paginate: 8
paginate_path: "/episdes/page:num/"
